version: '2'
services:
    catalogue-app:
        image: catalogue
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://catalogue-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=catalogue
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    catalogue-mongodb:
        extends:
            file: mongodb.yml
            service: catalogue-mongodb
