version: '2'
services:
    ui-app:
        image: ui
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ui-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ui
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ui-mongodb:
        extends:
            file: mongodb.yml
            service: ui-mongodb
