version: '2'
services:
    authentification-app:
        image: authentification
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://authentification-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=authentification
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    authentification-mongodb:
        extends:
            file: mongodb.yml
            service: authentification-mongodb
